// <auto-generated />
using System;
using LocMp.Analytics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocMp.Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.DisputeSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageResolutionMinutes")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("BuyerFavoredCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OpenedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ResolvedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SellerFavoredCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DisputeSummaries", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.GeographicActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveBuyers")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveSellers")
                        .HasColumnType("integer");

                    b.Property<Guid>("ComplexId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComplexName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("PeriodType")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId", "PeriodType", "PeriodStart")
                        .IsUnique();

                    b.ToTable("GeographicActivities", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.PlatformDailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveBuyers")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveSellers")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BlockedUsers")
                        .HasColumnType("integer");

                    b.Property<int>("CancelledOrders")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedOrders")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DisputedOrders")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossMerchandiseValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("NewProducts")
                        .HasColumnType("integer");

                    b.Property<int>("NewRegistrations")
                        .HasColumnType("integer");

                    b.Property<int>("NewReviews")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PlatformDailySummaries", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.ProductRatingSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("ProductRatingSummaries", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.ProductViewCounter", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalViews")
                        .HasColumnType("integer");

                    b.Property<int>("ViewsThisWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ViewsToday")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("ProductViewCounters", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.SellerLeaderboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<int>("OrderCountRank")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("PeriodType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RanksComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevenueRank")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PeriodType", "PeriodStart", "RevenueRank");

                    b.HasIndex("SellerId", "PeriodType", "PeriodStart")
                        .IsUnique();

                    b.ToTable("SellerLeaderboards", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.SellerRatingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<int>("NewReviewsToday")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RecordedAt")
                        .HasColumnType("date");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("SellerId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("SellerRatingHistory", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.SellerSalesSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<int>("DisputedCount")
                        .HasColumnType("integer");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("PeriodType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("SellerId", "PeriodType", "PeriodStart")
                        .IsUnique();

                    b.ToTable("SellerSalesSummaries", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.StockAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("ProductId", "AlertType");

                    b.HasIndex("SellerId", "IsAcknowledged");

                    b.ToTable("StockAlerts", "analytics");
                });

            modelBuilder.Entity("LocMp.Analytics.Domain.Entities.TopProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("PeriodType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalSold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("SellerId", "ProductId", "PeriodType", "PeriodStart")
                        .IsUnique();

                    b.ToTable("TopProducts", "analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
